//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 

namespace OSCSchema
{

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/office/outlook/2010/06/socialprovider.xsd")]
[System.Xml.Serialization.XmlRootAttribute("activityFeed", Namespace="http://schemas.microsoft.com/office/outlook/2010/06/socialprovider.xsd", IsNullable=false)]

public partial class activityFeedType {
    
    private string networkField;
    
    private activityDetailsType[] activitiesField;
    
    private activityTemplateContainerType[] templatesField;
    
    /// <remarks/>
    public string network {
        get {
            return this.networkField;
        }
        set {
            this.networkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("activityDetails", IsNullable=false)]
    public activityDetailsType[] activities {
        get {
            return this.activitiesField;
        }
        set {
            this.activitiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("activityTemplateContainer", IsNullable=false)]
    public activityTemplateContainerType[] templates {
        get {
            return this.templatesField;
        }
        set {
            this.templatesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/office/outlook/2010/06/socialprovider.xsd")]
public partial class activityDetailsType {
    
    private string ownerIDField;
    
    private string objectIDField;
    
    private ulong applicationIDField;
    
    private ulong templateIDField;
    
    private System.DateTime publishDateField;
    
    private activityTemplateTypeRestrictionType typeField;
    
    private bool typeFieldSpecified;
    
    private templateVariableType[] templateVariablesField;
    
    /// <remarks/>
    public string ownerID {
        get {
            return this.ownerIDField;
        }
        set {
            this.ownerIDField = value;
        }
    }
    
    /// <remarks/>
    public string objectID {
        get {
            return this.objectIDField;
        }
        set {
            this.objectIDField = value;
        }
    }
    
    /// <remarks/>
    public ulong applicationID {
        get {
            return this.applicationIDField;
        }
        set {
            this.applicationIDField = value;
        }
    }
    
    /// <remarks/>
    public ulong templateID {
        get {
            return this.templateIDField;
        }
        set {
            this.templateIDField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime publishDate {
        get {
            return this.publishDateField;
        }
        set {
            this.publishDateField = value;
        }
    }
    
    /// <remarks/>
    public activityTemplateTypeRestrictionType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool typeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("templateVariable", IsNullable=false)]
    public templateVariableType[] templateVariables {
        get {
            return this.templateVariablesField;
        }
        set {
            this.templateVariablesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/office/outlook/2010/06/socialprovider.xsd")]
public enum activityTemplateTypeRestrictionType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Status Update")]
    StatusUpdate,
    
    /// <remarks/>
    Photo,
    
    /// <remarks/>
    Document,
    
    /// <remarks/>
    Other,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/office/outlook/2010/06/socialprovider.xsd")]
public partial class templateVariableType {
    
    private string nameField;
    
    private string idField;
    
    private string nameHintField;
    
    private string emailAddressField;
    
    private string profileUrlField;
    
    private string textField;
    
    private string valueField;
    
    private string altTextField;
    
    private string hrefField;
    
    private simpleTemplateVariableType[] listItemsField;
    
    private templateTypeRestrictionType typeField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string nameHint {
        get {
            return this.nameHintField;
        }
        set {
            this.nameHintField = value;
        }
    }
    
    /// <remarks/>
    public string emailAddress {
        get {
            return this.emailAddressField;
        }
        set {
            this.emailAddressField = value;
        }
    }
    
    /// <remarks/>
    public string profileUrl {
        get {
            return this.profileUrlField;
        }
        set {
            this.profileUrlField = value;
        }
    }
    
    /// <remarks/>
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    public string altText {
        get {
            return this.altTextField;
        }
        set {
            this.altTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string href {
        get {
            return this.hrefField;
        }
        set {
            this.hrefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("simpleTemplateVariable", IsNullable=false)]
    public simpleTemplateVariableType[] listItems {
        get {
            return this.listItemsField;
        }
        set {
            this.listItemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public templateTypeRestrictionType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/office/outlook/2010/06/socialprovider.xsd")]
public partial class simpleTemplateVariableType {
    
    private string nameField;
    
    private string textField;
    
    private string valueField;
    
    private string altTextField;
    
    private string hrefField;
    
    private templateSimpleTypeRestrictionType typeField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    public string altText {
        get {
            return this.altTextField;
        }
        set {
            this.altTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string href {
        get {
            return this.hrefField;
        }
        set {
            this.hrefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public templateSimpleTypeRestrictionType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/office/outlook/2010/06/socialprovider.xsd")]
public enum templateSimpleTypeRestrictionType {
    
    /// <remarks/>
    linkVariable,
    
    /// <remarks/>
    textVariable,
    
    /// <remarks/>
    pictureVariable,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/office/outlook/2010/06/socialprovider.xsd")]
public partial class personAddressType {
    
    private string[] hashedAddressField;
    
    private int indexField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("hashedAddress")]
    public string[] hashedAddress {
        get {
            return this.hashedAddressField;
        }
        set {
            this.hashedAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int index {
        get {
            return this.indexField;
        }
        set {
            this.indexField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/office/outlook/2010/06/socialprovider.xsd")]
public partial class activityTemplateType {
    
    private activityTemplateTypeRestrictionType typeField;
    
    private bool typeFieldSpecified;
    
    private string titleField;
    
    private string dataField;
    
    private string iconField;
    
    /// <remarks/>
    public activityTemplateTypeRestrictionType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool typeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string icon {
        get {
            return this.iconField;
        }
        set {
            this.iconField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/office/outlook/2010/06/socialprovider.xsd")]
public partial class activityTemplateContainerType {
    
    private ulong applicationIDField;
    
    private ulong templateIDField;
    
    private activityTemplateType activityTemplateField;
    
    /// <remarks/>
    public ulong applicationID {
        get {
            return this.applicationIDField;
        }
        set {
            this.applicationIDField = value;
        }
    }
    
    /// <remarks/>
    public ulong templateID {
        get {
            return this.templateIDField;
        }
        set {
            this.templateIDField = value;
        }
    }
    
    /// <remarks/>
    public activityTemplateType activityTemplate {
        get {
            return this.activityTemplateField;
        }
        set {
            this.activityTemplateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/office/outlook/2010/06/socialprovider.xsd")]
public enum templateTypeRestrictionType {
    
    /// <remarks/>
    publisherVariable,
    
    /// <remarks/>
    entityVariable,
    
    /// <remarks/>
    linkVariable,
    
    /// <remarks/>
    textVariable,
    
    /// <remarks/>
    pictureVariable,
    
    /// <remarks/>
    listVariable,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/outlook/2010/06/socialprovider.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/outlook/2010/06/socialprovider.xsd", IsNullable=false)]
public partial class capabilities {
    
    private bool getFriendsField;
    
    private bool cacheFriendsField;
    
    private bool followPersonField;
    
    private bool doNotFollowPersonField;
    
    private bool getActivitiesField;
    
    private bool cacheActivitiesField;
    
    private bool dynamicActivitiesLookupField;
    
    private bool dynamicActivitiesLookupFieldSpecified;
    
    private bool displayUrlField;
    
    private bool useLogonWebAuthField;
    
    private bool hideHyperlinksField;
    
    private bool hideHyperlinksFieldSpecified;
    
    private bool supportsAutoConfigureField;
    
    private bool supportsAutoConfigureFieldSpecified;
    
    private uint contactSyncRestartIntervalField;
    
    private bool contactSyncRestartIntervalFieldSpecified;
    
    private bool dynamicActivitiesLookupExField;
    
    private bool dynamicActivitiesLookupExFieldSpecified;
    
    private bool dynamicContactsLookupField;
    
    private bool dynamicContactsLookupFieldSpecified;
    
    private bool useLogonCachedField;
    
    private bool useLogonCachedFieldSpecified;
    
    private bool hideRememberMyPasswordField;
    
    private bool hideRememberMyPasswordFieldSpecified;
    
    private string createAccountUrlField;
    
    private string forgotPasswordUrlField;
    
    private bool showOnDemandActivitiesWhenMinimizedField;
    
    private bool showOnDemandActivitiesWhenMinimizedFieldSpecified;
    
    private bool showOnDemandContactsWhenMinimizedField;
    
    private bool showOnDemandContactsWhenMinimizedFieldSpecified;
    
    private string hashFunctionField;
    
    /// <remarks/>
    public bool getFriends {
        get {
            return this.getFriendsField;
        }
        set {
            this.getFriendsField = value;
        }
    }
    
    /// <remarks/>
    public bool cacheFriends {
        get {
            return this.cacheFriendsField;
        }
        set {
            this.cacheFriendsField = value;
        }
    }
    
    /// <remarks/>
    public bool followPerson {
        get {
            return this.followPersonField;
        }
        set {
            this.followPersonField = value;
        }
    }
    
    /// <remarks/>
    public bool doNotFollowPerson {
        get {
            return this.doNotFollowPersonField;
        }
        set {
            this.doNotFollowPersonField = value;
        }
    }
    
    /// <remarks/>
    public bool getActivities {
        get {
            return this.getActivitiesField;
        }
        set {
            this.getActivitiesField = value;
        }
    }
    
    /// <remarks/>
    public bool cacheActivities {
        get {
            return this.cacheActivitiesField;
        }
        set {
            this.cacheActivitiesField = value;
        }
    }
    
    /// <remarks/>
    public bool dynamicActivitiesLookup {
        get {
            return this.dynamicActivitiesLookupField;
        }
        set {
            this.dynamicActivitiesLookupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dynamicActivitiesLookupSpecified {
        get {
            return this.dynamicActivitiesLookupFieldSpecified;
        }
        set {
            this.dynamicActivitiesLookupFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool displayUrl {
        get {
            return this.displayUrlField;
        }
        set {
            this.displayUrlField = value;
        }
    }
    
    /// <remarks/>
    public bool useLogonWebAuth {
        get {
            return this.useLogonWebAuthField;
        }
        set {
            this.useLogonWebAuthField = value;
        }
    }
    
    /// <remarks/>
    public bool hideHyperlinks {
        get {
            return this.hideHyperlinksField;
        }
        set {
            this.hideHyperlinksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool hideHyperlinksSpecified {
        get {
            return this.hideHyperlinksFieldSpecified;
        }
        set {
            this.hideHyperlinksFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool supportsAutoConfigure {
        get {
            return this.supportsAutoConfigureField;
        }
        set {
            this.supportsAutoConfigureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool supportsAutoConfigureSpecified {
        get {
            return this.supportsAutoConfigureFieldSpecified;
        }
        set {
            this.supportsAutoConfigureFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public uint contactSyncRestartInterval {
        get {
            return this.contactSyncRestartIntervalField;
        }
        set {
            this.contactSyncRestartIntervalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool contactSyncRestartIntervalSpecified {
        get {
            return this.contactSyncRestartIntervalFieldSpecified;
        }
        set {
            this.contactSyncRestartIntervalFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool dynamicActivitiesLookupEx {
        get {
            return this.dynamicActivitiesLookupExField;
        }
        set {
            this.dynamicActivitiesLookupExField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dynamicActivitiesLookupExSpecified {
        get {
            return this.dynamicActivitiesLookupExFieldSpecified;
        }
        set {
            this.dynamicActivitiesLookupExFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool dynamicContactsLookup {
        get {
            return this.dynamicContactsLookupField;
        }
        set {
            this.dynamicContactsLookupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dynamicContactsLookupSpecified {
        get {
            return this.dynamicContactsLookupFieldSpecified;
        }
        set {
            this.dynamicContactsLookupFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool useLogonCached {
        get {
            return this.useLogonCachedField;
        }
        set {
            this.useLogonCachedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool useLogonCachedSpecified {
        get {
            return this.useLogonCachedFieldSpecified;
        }
        set {
            this.useLogonCachedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool hideRememberMyPassword {
        get {
            return this.hideRememberMyPasswordField;
        }
        set {
            this.hideRememberMyPasswordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool hideRememberMyPasswordSpecified {
        get {
            return this.hideRememberMyPasswordFieldSpecified;
        }
        set {
            this.hideRememberMyPasswordFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string createAccountUrl {
        get {
            return this.createAccountUrlField;
        }
        set {
            this.createAccountUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string forgotPasswordUrl {
        get {
            return this.forgotPasswordUrlField;
        }
        set {
            this.forgotPasswordUrlField = value;
        }
    }
    
    /// <remarks/>
    public bool showOnDemandActivitiesWhenMinimized {
        get {
            return this.showOnDemandActivitiesWhenMinimizedField;
        }
        set {
            this.showOnDemandActivitiesWhenMinimizedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool showOnDemandActivitiesWhenMinimizedSpecified {
        get {
            return this.showOnDemandActivitiesWhenMinimizedFieldSpecified;
        }
        set {
            this.showOnDemandActivitiesWhenMinimizedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool showOnDemandContactsWhenMinimized {
        get {
            return this.showOnDemandContactsWhenMinimizedField;
        }
        set {
            this.showOnDemandContactsWhenMinimizedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool showOnDemandContactsWhenMinimizedSpecified {
        get {
            return this.showOnDemandContactsWhenMinimizedFieldSpecified;
        }
        set {
            this.showOnDemandContactsWhenMinimizedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string hashFunction {
        get {
            return this.hashFunctionField;
        }
        set {
            this.hashFunctionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/outlook/2010/06/socialprovider.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/outlook/2010/06/socialprovider.xsd", IsNullable=false)]
public partial class hashedAddresses {
    
    private personAddressType[] personAddressesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("personAddresses")]
    public personAddressType[] personAddresses {
        get {
            return this.personAddressesField;
        }
        set {
            this.personAddressesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/outlook/2010/06/socialprovider.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/outlook/2010/06/socialprovider.xsd", IsNullable=false)]
public partial class friends {
    
    private personType[] personField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("person")]
    public personType[] person {
        get {
            return this.personField;
        }
        set {
            this.personField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/office/outlook/2010/06/socialprovider.xsd")]
[System.Xml.Serialization.XmlRootAttribute("person", Namespace="http://schemas.microsoft.com/office/outlook/2010/06/socialprovider.xsd", IsNullable=false)]
public partial class personType {
    
    private string userIDField;
    
    private string firstNameField;
    
    private string lastNameField;
    
    private string fullNameField;
    
    private string nicknameField;
    
    private string fileAsField;
    
    private string companyField;
    
    private string titleField;
    
    private System.DateTime anniversaryField;
    
    private bool anniversaryFieldSpecified;
    
    private System.DateTime birthdayField;
    
    private bool birthdayFieldSpecified;
    
    private string emailAddressField;
    
    private string emailAddress2Field;
    
    private string emailAddress3Field;
    
    private string webProfilePageField;
    
    private string phoneField;
    
    private string cellField;
    
    private string homePhoneField;
    
    private string workPhoneField;
    
    private string addressField;
    
    private string cityField;
    
    private string stateField;
    
    private string countryOrRegionField;
    
    private string zipField;
    
    private string relationshipField;
    
    private System.DateTime creationTimeField;
    
    private bool creationTimeFieldSpecified;
    
    private System.DateTime lastModificationTimeField;
    
    private bool lastModificationTimeFieldSpecified;
    
    private System.DateTime expirationTimeField;
    
    private bool expirationTimeFieldSpecified;
    
    private string genderField;
    
    private int indexField;
    
    private bool indexFieldSpecified;
    
    private string pictureUrlField;
    
    private string friendStatusField;
    
    /// <remarks/>
    public string userID {
        get {
            return this.userIDField;
        }
        set {
            this.userIDField = value;
        }
    }
    
    /// <remarks/>
    public string firstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    public string lastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    public string fullName {
        get {
            return this.fullNameField;
        }
        set {
            this.fullNameField = value;
        }
    }
    
    /// <remarks/>
    public string nickname {
        get {
            return this.nicknameField;
        }
        set {
            this.nicknameField = value;
        }
    }
    
    /// <remarks/>
    public string fileAs {
        get {
            return this.fileAsField;
        }
        set {
            this.fileAsField = value;
        }
    }
    
    /// <remarks/>
    public string company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime anniversary {
        get {
            return this.anniversaryField;
        }
        set {
            this.anniversaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool anniversarySpecified {
        get {
            return this.anniversaryFieldSpecified;
        }
        set {
            this.anniversaryFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime birthday {
        get {
            return this.birthdayField;
        }
        set {
            this.birthdayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool birthdaySpecified {
        get {
            return this.birthdayFieldSpecified;
        }
        set {
            this.birthdayFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string emailAddress {
        get {
            return this.emailAddressField;
        }
        set {
            this.emailAddressField = value;
        }
    }
    
    /// <remarks/>
    public string emailAddress2 {
        get {
            return this.emailAddress2Field;
        }
        set {
            this.emailAddress2Field = value;
        }
    }
    
    /// <remarks/>
    public string emailAddress3 {
        get {
            return this.emailAddress3Field;
        }
        set {
            this.emailAddress3Field = value;
        }
    }
    
    /// <remarks/>
    public string webProfilePage {
        get {
            return this.webProfilePageField;
        }
        set {
            this.webProfilePageField = value;
        }
    }
    
    /// <remarks/>
    public string phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    public string cell {
        get {
            return this.cellField;
        }
        set {
            this.cellField = value;
        }
    }
    
    /// <remarks/>
    public string homePhone {
        get {
            return this.homePhoneField;
        }
        set {
            this.homePhoneField = value;
        }
    }
    
    /// <remarks/>
    public string workPhone {
        get {
            return this.workPhoneField;
        }
        set {
            this.workPhoneField = value;
        }
    }
    
    /// <remarks/>
    public string address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public string city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public string countryOrRegion {
        get {
            return this.countryOrRegionField;
        }
        set {
            this.countryOrRegionField = value;
        }
    }
    
    /// <remarks/>
    public string zip {
        get {
            return this.zipField;
        }
        set {
            this.zipField = value;
        }
    }
    
    /// <remarks/>
    public string relationship {
        get {
            return this.relationshipField;
        }
        set {
            this.relationshipField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime creationTime {
        get {
            return this.creationTimeField;
        }
        set {
            this.creationTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool creationTimeSpecified {
        get {
            return this.creationTimeFieldSpecified;
        }
        set {
            this.creationTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime lastModificationTime {
        get {
            return this.lastModificationTimeField;
        }
        set {
            this.lastModificationTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lastModificationTimeSpecified {
        get {
            return this.lastModificationTimeFieldSpecified;
        }
        set {
            this.lastModificationTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime expirationTime {
        get {
            return this.expirationTimeField;
        }
        set {
            this.expirationTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool expirationTimeSpecified {
        get {
            return this.expirationTimeFieldSpecified;
        }
        set {
            this.expirationTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string gender {
        get {
            return this.genderField;
        }
        set {
            this.genderField = value;
        }
    }
    
    /// <remarks/>
    public int index {
        get {
            return this.indexField;
        }
        set {
            this.indexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool indexSpecified {
        get {
            return this.indexFieldSpecified;
        }
        set {
            this.indexFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string pictureUrl {
        get {
            return this.pictureUrlField;
        }
        set {
            this.pictureUrlField = value;
        }
    }
    
    /// <remarks/>
    public string friendStatus {
        get {
            return this.friendStatusField;
        }
        set {
            this.friendStatusField = value;
        }
    }
   }
}
